// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/dist/lib/metadata/types/metadata-interface.js"

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}


// Validate ../../src/app/case-studies/design-system/page.tsx
{
  const handler = {} as typeof import("../../src/app/case-studies/design-system/page.js")
  handler satisfies AppPageConfig<"/case-studies/design-system">
}

// Validate ../../src/app/case-studies/draw-management/page.tsx
{
  const handler = {} as typeof import("../../src/app/case-studies/draw-management/page.js")
  handler satisfies AppPageConfig<"/case-studies/draw-management">
}

// Validate ../../src/app/case-studies/enterprise-replatform/page.tsx
{
  const handler = {} as typeof import("../../src/app/case-studies/enterprise-replatform/page.js")
  handler satisfies AppPageConfig<"/case-studies/enterprise-replatform">
}

// Validate ../../src/app/case-studies/highlight-reel/page.tsx
{
  const handler = {} as typeof import("../../src/app/case-studies/highlight-reel/page.js")
  handler satisfies AppPageConfig<"/case-studies/highlight-reel">
}

// Validate ../../src/app/page.tsx
{
  const handler = {} as typeof import("../../src/app/page.js")
  handler satisfies AppPageConfig<"/">
}

// Validate ../../src/app/portfolio/page.tsx
{
  const handler = {} as typeof import("../../src/app/portfolio/page.js")
  handler satisfies AppPageConfig<"/portfolio">
}

// Validate ../../src/app/writing/page.tsx
{
  const handler = {} as typeof import("../../src/app/writing/page.js")
  handler satisfies AppPageConfig<"/writing">
}







// Validate ../../src/app/layout.tsx
{
  const handler = {} as typeof import("../../src/app/layout.js")
  handler satisfies LayoutConfig<"/">
}
